# -*- coding: utf-8 -*-
"""Копия блокнота "Python.ipynb"

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Cjg2LBicUJXFCIn601FTPtcj_wY5ej4c
"""

import pandas as pd
import random


lst = ['robot'] * 10
lst += ['human'] * 10
random.shuffle(lst)
data = pd.DataFrame({'whoAmI': lst})

data.reset_index(inplace=True)
data_one_hot = pd.get_dummies(data['whoAmI'])
data_one_hot.columns = ['whoAmI_' + str(col) for col in data_one_hot.columns]
data = data.merge(data_one_hot, left_index=True, right_index=True)
data.drop('whoAmI', axis=1, inplace=True)

data.head()

